apiVersion: v1
kind: ConfigMap
metadata:
  name: sprouts-config
  namespace: sprouts
  labels:
    app.kubernetes.io/name: sprouts
data:
  APP_ENV: "development"
  RUST_LOG: "info"
  BIND_ADDRESS: "0.0.0.0:3000"
  DATABASE_MAX_CONNECTIONS: "5"
  POSTGRES_USER: "admin"
  POSTGRES_DB: "sprouts"
