apiVersion: v1
kind: Secret
metadata:
  name: sprouts-secret
  namespace: sprouts
  labels:
    app.kubernetes.io/name: sprouts
type: Opaque
stringData:
  POSTGRES_PASSWORD: "admin"
  DATABASE_URL: "postgres://admin:admin@database:5432/sprouts"
